export interface Donation {
  donationId: number,
  supporterId: number,
  donationType: string,
  donationDate: string,
  isRecurring: boolean,
  recurringFrequency?: string | null,
  campaignName?: string | null,
  channelSource: string,
  currencyCode?: string | null,
  amount?: number | null,
  estimatedValue: number,
  impactUnit: string,
  notes?: string | null,
  referralPostId?: number | null,
}
