export interface Resident {
  residentId: number,
  caseControlNo: string,
  internalCode: string,
  safehouseId: number,
  caseStatus: string,
  sex: string,
  dateOfBirth: string,
  birthStatus: string,
  placeOfBirth: string,
  religion: string,
  caseCategory: string,
  subCatOrphaned: boolean,
  subCatTrafficked: boolean,
  subCatChildLabor: boolean,
  subCatPhysicalAbuse: boolean,
  subCatSexualAbuse: boolean,
  subCatOsaec: boolean,
  subCatCicl: boolean,
  subCatAtRisk: boolean,
  subCatStreetChild: boolean,
  subCatChildWithHiv: boolean,
  isPwd: boolean,
  pwdType?: string | null,
  hasSpecialNeeds: boolean,
  specialNeedsDiagnosis?: string | null,
  familyIs4ps: boolean,
  familySoloParent: boolean,
  familyIndigenous: boolean,
  familyParentPwd: boolean,
  familyInformalSettler: boolean,
  dateOfAdmission: string,
  ageUponAdmission: string,
  presentAge: string,
  lengthOfStay: string,
  referralSource?: string | null,
  referringAgencyPerson?: string | null,
  dateColbRegistered?: string | null,
  dateColbObtained?: string | null,
  assignedSocialWorker?: string | null,
  initialCaseAssessment?: string | null,
  dateCaseStudyPrepared?: string | null,
  reintegrationType?: string | null,
  reintegrationStatus?: string | null,
  initialRiskLevel?: string | null,
  currentRiskLevel?: string | null,
  dateEnrolled?: string | null,
  dateClosed?: string | null,
  createdAt?: string | null,
  notesRestricted?: string | null,
}
