export interface SocialMediaPost {
  postId: number,
  platform: string,
  platformPostId: string,
  postUrl: string,
  createdAt: string,
  dayOfWeek: string,
  postHour: number,
  postType: string,
  mediaType: string,
  caption: string,
  hashtags?: string | null,
  numHashtags: number,
  mentionsCount: number,
  hasCallToAction: boolean,
  callToActionType?: string | null,
  contentTopic: string,
  sentimentTone: string,
  captionLength: number,
  featuresResidentStory: boolean,
  campaignName?: string | null,
  isBoosted: boolean,
  boostBudgetPhp?: number | null,
  impressions: number,
  reach: number,
  likes: number,
  comments: number,
  shares: number,
  saves: number,
  clickThroughs: number,
  videoViews?: number | null,
  engagementRate: number,
  profileVisits: number,
  donationReferrals: number,
  estimatedDonationValuePhp: number,
  followerCountAtPost: number,
  watchTimeSeconds?: number | null,
  avgViewDurationSeconds?: number | null,
  subscriberCountAtPost?: number | null,
  forwards?: number | null,
}
